# Generated by Django 4.2 on 2023-04-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expires',
            field=models.DateField(null=True, verbose_name='Expira em'),
        ),
    ]
