# Generated by Django 4.2 on 2023-05-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='browser',
            field=models.CharField(max_length=255, null=True, verbose_name='navegador'),
        ),
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.CharField(max_length=255, null=True, verbose_name='dispositivo'),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_adress',
            field=models.CharField(max_length=255, null=True, verbose_name='ip do usuario'),
        ),
    ]
