# Generated by Django 4.2 on 2023-05-04 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_user_browser_remove_user_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(max_length=255, null=True, verbose_name='navegador do usuario')),
                ('device', models.CharField(max_length=255, null=True, verbose_name='dispositivo do usuario')),
                ('ip_address', models.CharField(max_length=255, null=True, verbose_name='ip do usuario')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Acesso',
                'verbose_name_plural': 'Acessos',
            },
        ),
    ]
