# Generated by Django 4.2 on 2023-05-04 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_logacess'),
    ]

    operations = [
        migrations.AddField(
            model_name='logacess',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
    ]
