# Generated by Django 4.2 on 2023-05-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_allcookies_options_allcookies_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('ADHEART', 'Adheart'), ('ADSPY', 'Adspy'), ('ADVAULT', 'Advault'), ('PIPIADS', 'Pipiads'), ('BISPY', 'Bispy'), ('ADHEART2', 'Adheart2'), ('SYSTEMTESTE', 'Systemteste')], max_length=100, verbose_name='Nome'),
        ),
    ]
